# Generated by Django 3.0.8 on 2020-07-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=56)),
                ('year', models.IntegerField()),
                ('gearbox', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=2)),
                ('color', models.CharField(max_length=128)),
            ],
        ),
    ]
